### ISSUE TITLE
Add the Class info for the Controller

### ISSUE THREAD

**Issue by petecorbs** [Minhazulmin/laravel-11-QR-Code-Generate#4]
for this to work you must import the class into your controller

use SimpleSoftwareIO\QrCode\Facades\QrCode;

**Comment by Minhazulmin** [comment]
@petecorbs 
We greatly appreciate the valuable input you have provided us with. Your feedback is incredibly important to us and we are grateful for the time and effort you have taken to share your thoughts and opinions. Thank you for taking the time to provide us with your feedback, as it helps us to continually improve and enhance our services.

**I disagree with your statement because the functionality is already present in the controller.**

https://github.com/Minhazulmin/laravel-10-QR-Code-Generate/blob/main/app/Http/Controllers/QRcodeGenerateController.php#L5

**Comment by petecorbs** [comment]
People use these (Github) packages as part of other existing installations to enhance or offer features to an existing project, so your controller won't be used or seen unless someone looks through your folders, I installed the package from the command line using composer, I then followed the basic instructions in your tutorial (your instructions tell users to create a controller not open and copy yours), I wasn't commenting as a criticism I was simply placing the info there for other users to have quick access to the class as without it your tutorial doesn't work.
